name: CI/CD Next.js with Prisma

on:
  push:
    branches:
      - staging # Ganti dengan branch yang Anda gunakan untuk deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install # Menggunakan Yarn untuk menginstal dependencies

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Menggunakan secrets
          EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
          EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
        run: npx prisma migrate deploy

      - name: Build Next.js application
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Menggunakan secrets
          EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
          EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
        run: yarn build # Menggunakan Yarn untuk build aplikasi

      - name: Deploy to VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }} # Menggunakan secret untuk password VPS
        run: |
          # Menggunakan sshpass untuk mengotentikasi dengan password
          sudo apt-get install -y sshpass # Instal sshpass

          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh root@178.128.17.214 << 'EOF'
            # Hentikan aplikasi yang berjalan (jika menggunakan PM2)
            pm2 stop backoffice || true

            # Hapus folder build lama
            rm -rf /root/project/backoffice/.next

            # Copy file hasil build ke server
            rsync -avz --delete .next/ root@178.128.17.214:/root/project/backoffice/.next/
            rsync -avz --delete package.json yarn.lock root@178.128.17.214:/root/project/backoffice/

            # Masuk ke folder deployment
            cd /root/project/backoffice/

            # Install dependencies (jika perlu)
            yarn install  # Menggunakan Yarn untuk menginstal dependencies

            # Restart aplikasi
            pm2 start backoffice
          EOF
